### ISSUE TITLE
Wiki for how to link everything

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/disaster-resilience#11]

**Comment by sky-t** [comment]
I believe after the last meeting, we were hoping that jupyterdrive or some other type of Google Drive integration for jupyter notebooks might be the solution for this. After testing jupyterdrive this week, so far I don't think it's the right solution for us due lack or access to shared Hack OR Google Drive files, and also some error messages I got when activating the notebook extension (although @sowright seemed to have a clean install). I've also tried pydrive with a similar result of not being to see shared files. 

Given all this we'll need to regroup next meeting but it may make more sense for us to continue to just dump files into our team Google Drive data folder and then each of us can pull them into our own local install of potgres or QGIS as we explore the data. Once we have a team AWS instance we can then centralize everything.

**Comment by sky-t** [comment]
since the jupyter drive option is not viable, I'm closing this issue
