### ISSUE TITLE
Clean up PBEM survey data set

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/disaster-resilience#18]

**Comment by LepoutreA** [comment]
Preliminary findings:
-spatial constraints at zip code level (concentrated at centroid of zip code).
-survey seems to be have quite a few questions with free flowing answers which could be difficult to analyze.
 
Based on these, let's create index of columns of with classifcation (interesting, not interesting).

**Comment by LepoutreA** [comment]
I am going to close this issue until we decide whether we use it or not. We can reopen it in case we end up using the PBEM data.

**Comment by rcallihan** [comment]
I agree, the spatial units (zip centroids) and data cleanliness issues would make this dataset too difficult to analyze with any great spatial detail.  Though, we still may use some of this data in aggregate in our data visualization, something like 'xx% of respondents in Portland think....". We can close this for now, we'll need to keep this dataset in our backpocket just in case.
