### ISSUE TITLE
Share Disaster Response ACS tables to Neighborhood team

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/disaster-resilience#26]

**Comment by sky-t** [comment]
@catnik who in the Neighborhood Development team should I work with on this?

**Comment by PoeStewart** [comment]
Hey Scott,

Zachary Neumann is their data manager (zachary@hackoregon.org).

Thanks,

Poe

**Comment by sky-t** [comment]
thx @PoeStewart, I emailed Zachary today and introduced myself to see if I can be helpful.

**Comment by znmeb** [comment]
Transportation Systems also wants ACS data - Brian Grant is the data manager but I'm doing most of the GIS stuff.
