### ISSUE TITLE
Talk with Michael Lange about what we have to do with the datastage, give a single data set and see if they can get us up there, make a local API to get some data output.

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/disaster-resilience#35]

**Comment by mxmoss** [comment]
working with michael and @maryannet we worked out a plan for sharing the database.
Here's the summary:
1) Use docker containers to run the postgres database. 
Here's the quickstart for that
https://github.com/hackoregon/data-science-pet-containers#quick-start

2) Each person will run a copy of the disaster.backup database in a container
The disaster.backup contains vector and non-GIS tables.
This copy is for personal research & experiments.

3) A shared S3 bucket will serve up the raster data for disaster.
The raster files are large so they're difficult to copy around. 

4) eventually, the Postgres database will be hosted on AWS and served up through a Django API.
This will the production database.

Here is a schematic showing how this system will work:
https://docs.google.com/drawings/d/1RrH-xGXtmKsbVQ_AiKFJZC8-nfxgpSaXROUo3QG16vY/edit?usp=sharing
