### ISSUE TITLE
Convert DOGAMI ESRI rasters to format compatible with QGIS and GDAL geoprocessing tools

### ISSUE THREAD

**Issue by LepoutreA** [hackoregon/disaster-resilience#38]
The dataset of raster needs to be converted to a different format than ESRI rasters. I will work to load them in ArcGIs and convert them to .TIFFs.

**Comment by rcallihan** [comment]
We can work on this tomorrow, as it will mostly be day to knock out tasks. We should go ahead and convert them to the appropriate spatial reference at this stage as well.

**Comment by LepoutreA** [comment]
Yeah I agree that tomorrow would be a good day for an applied work session. I have to use  esri to convert them (according to  https://gis.stackexchange.com/questions/236332/converting-esri-raster-dataset-to-qgis-compatible-dataset) so I might try to do it today in GIS.
