### ISSUE TITLE
Connect with Scott about the census (and ACS) data and see if we can update it to the latest info

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/disaster-resilience#43]

**Comment by rcallihan** [comment]
I've connected with @sky-t on this and also queried the rest of Hack Oregon about any unifying Census dataset that we're using for this project cycle. It appears there is no standard dataset we're using, so we'll have to come up with. 

I'll set up another task for getting updated 2016 ACS data to the block group. Hopefully we have a workflow from that @sky-t used last year that we can repeat with 2016 data.
