### ISSUE TITLE
Retrieve and prep 2016 ACS/Census block groups and select demographic variables. 

### ISSUE THREAD

**Issue by rcallihan** [hackoregon/disaster-resilience#44]
We'll grab updated 2016 ACS 5-year estimates in the same fashion we did for Emergency Response. It's likely other teams across Hack Oregon will be using this data.

**Comment by znmeb** [comment]
What format will that be? A PostgreSQL database dump (pg_dump)?

**Comment by rcallihan** [comment]
@znmeb We're working with the tri-county area in #disaster, so we'll be getting Clackamas and Washington as well. The data will be a shp to start, as we'll be joining Census tables to Tigerline blockgroup shps. We can convert from there.

**Comment by znmeb** [comment]
That should work for us then. Are you using the pre-joined data or doing your own joins?

**Comment by znmeb** [comment]
Oh, yeah - the code ;-)

```
ogr2ogr -f SQLite ACS_2016_5YR_BG_41.sqlite ACS_2016_5YR_BG_41.gdb.zip
spatialite_gui ACS_2016_5YR_BG_41.sqlite &
```

**Comment by sky-t** [comment]
I went into the American Fact Finder and, using the Social Vulnerability Index variables as a guide, downloaded, these tables from the 2016 ACS five year estimates for census block groups. 
Tables:
B01003 - TOTAL POPULATION
B25001 - HOUSING UNITS
B25009 - TENURE BY HOUSEHOLD SIZE
B17017 - POVERTY STATUS IN THE PAST 12 MONTHS BY HOUSEHOLD TYPE BY AGE OF HOUSEHOLDER
B01001 - SEX BY AGE
B99012 - ALLOCATION OF AGE
B27010 - TYPES OF HEALTH INSURANCE COVERAGE BY AGE
B19001 - HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS)
B19301 - PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS)
B19013 - MEDIAN HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS)
B22010 - RECEIPT OF FOOD STAMPS/SNAP IN THE PAST 12 MONTHS BY DISABILITY STATUS FOR HOUSEHOLDS
B23024 - POVERTY STATUS IN THE PAST 12 MONTHS BY DISABILITY STATUS BY EMPLOYMENT STATUS FOR THE POPULATION 20 TO 64 YEARS
B23025 - EMPLOYMENT STATUS FOR THE POPULATION 16 YEARS AND OVER
B23008 - AGE OF OWN CHILDREN UNDER 18 YEARS IN FAMILIES AND SUBFAMILIES BY LIVING ARRANGEMENTS BY EMPLOYMENT STATUS OF PARENTS
B99161 - ALLOCATION OF LANGUAGE STATUS FOR THE POPULATION 5 YEARS AND OVER
B99163 - ALLOCATION OF ABILITY TO SPEAK ENGLISH FOR THE POPULATION 5 YEARS AND OVER
B25024 - UNITS IN STRUCTURE
B25035 - MEDIAN YEAR STRUCTURE BUILT
B25034 - YEAR STRUCTURE BUILT
B25033 - TOTAL POPULATION IN OCCUPIED HOUSING UNITS BY TENURE BY UNITS IN STRUCTURE
B15003 - EDUCATIONAL ATTAINMENT FOR THE POPULATION 25 YEARS AND OVER
Geographies:
All Block Groups within Oregon

**Comment by znmeb** [comment]
Thanks! That will probably work for us - hit me up in Slack when you have it collected. I may end up going back in time a few years with the same variables to merge with our ridership data, which spans ten years.
