### ISSUE TITLE
Work With Ed on docker instance

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/disaster-resilience#48]

**Comment by znmeb** [comment]
Ready when you are ;-)

What do you need?

**Comment by znmeb** [comment]
Latest release of Data Science Pet Containers is posted - https://github.com/hackoregon/data-science-pet-containers/releases/tag/v2.0.0

I don't have any plans to push anything new to master now that there are other teams using this besides Transportation Systems, so you can pull from master and file issues just like any other normal open source community project ;-)

**Comment by mxmoss** [comment]
hi @znmeb . didn't get a chance to work on it yesterday.
i'll try it out tomorrow...

**Comment by znmeb** [comment]
I'm planning to come to the next meeting - check Slack

**Comment by maryannet** [comment]
containers exist

**Comment by znmeb** [comment]
I just posted a release - a lot more can be automated now. See https://github.com/hackoregon/data-science-pet-containers/tree/master/examples/reowning_a_database
