### ISSUE TITLE
Setup PostGres on AWS instance

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/disaster-resilience#6]

**Comment by PoeStewart** [comment]
A general consideration that we'll all need access to it

**Comment by znmeb** [comment]
Do you need two instances - one with just PostgreSQL and one with PostgreSQL + PostGIS?

**Comment by LepoutreA** [comment]
Hello, I believe we would only need one instance with PostgresSQL +PostGIS. Ryan or Mary-Anne,  can you confirm to be 100% sure.

**Comment by maryannet** [comment]
We need postgreSQL + PostGis instance as soon as we can get it done. Currently have docker containers

**Comment by znmeb** [comment]
So are you standing up a new instance or using the one from last year?
