### ISSUE TITLE
Setup PostGis instance on AWS

### ISSUE THREAD

**Issue by PoeStewart** [hackoregon/disaster-resilience#7]

**Comment by PoeStewart** [comment]
A general consideration that we'll all need access to it

**Comment by znmeb** [comment]
I have a Docker image for PostGIS on Docker Hub. See https://hub.docker.com/r/znmeb/postgis/

Usage is the same as the official PostgreSQL image at https://store.docker.com/images/postgres

Do you need geocoding?
